version: "3.9"
services:
  fastapi:
    environment:
      - API_NOCACHE=0
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
    #hot reloading of fastapi app
    - type: bind
      source: ./api
      target: /api/api
    ports:
      - 80:5000
    restart: unless-stopped
  redis:
    container_name: local-redis
    image: redis/redis-stack
    ports: 
      - 6379:6379
    restart: on-failure
  

