name: Publish to Dockerhub

on:
  release:
    types: [published]

jobs:
  push_to_dockerhub:
    name: Push Docker Image to Dockerhub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata for dockerhub
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: iqunlim/vgmsite-fastapi
            
      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

        