name: Pytest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  AWS_REGION : "us-east-1"

jobs:
  test:
    runs-on: ubuntu-latest
    # Perms for openID Connect for AWS
    # See: https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
    permissions: 
      id-token: write 
      contents: read
    steps:

      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12
          architecture: 'x64'
          cache: 'pip'
          
      - name: Install Depenencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade -r requirements.txt

      - name: Setup Logging Module
        run: |
          mkdir ${{ github.workspace }}/logs
          touch ${{ github.workspace }}/logs/fastapi.log

      - name: Configure AWS Credentials for DynamoDB
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::172297794992:role/github-vgmapi # Set up in Identity providers in IAM Console and connected to gituhub-vgmapi
          role-session-name: vgmapi-workflow-pytest
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Run pytest
        run: |
          python -m pytest tests/
